name: Clang-Format Workflow

on:
  push:
    branches: '**'
  pull_request:

jobs:
  format:
    name: Check the formatting
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          submodules: recursive

      - name: Run clang-format
        env:
            RED4EXT_COMMIT_BEFORE: ${{ github.event.pull_request.base.sha || github.event.before }}
            RED4EXT_COMMIT_AFTER: ${{ github.sha }}
        run: |
          $output = (git `
                      -c core.autocrlf=false `
                      -c core.eol=lf `
                      -c color.ui=always `
                      clang-format `
                        --style file `
                        --diff $env:RED4EXT_COMMIT_BEFORE $env:RED4EXT_COMMIT_AFTER
                    )?.Trim()

          Write-Output $output

          if ($output -ne $null -and $output -ine "no modified files to format") {
            exit 1
          }
