name: Clang-Format Workflow

on:
  push:
    branches: '**'
    paths:
      - '**.hpp'
      - '**.cpp'
  pull_request:
    paths:
      - '**.hpp'
      - '**.cpp'

env:
  LLVM_VERSION: 16

jobs:
  format:
    name: Check the formatting
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Pin to a specific version
        run: |
          $latestChocoVersion = (Get-LatestChocoPackageVersion -TargetVersion $env:LLVM_VERSION -PackageName "llvm")
          Choco-Install -PackageName llvm -ArgumentList '--allow-downgrade', '--version', $latestChocoVersion

      - name: Run clang-format
        env:
            RED3EXT_COMMIT_BEFORE: ${{ github.event.pull_request.base.sha || github.event.before }}
            RED3EXT_COMMIT_AFTER: ${{ github.sha }}
        run: |
          git `
            -c core.autocrlf=false `
            -c core.eol=lf `
            -c color.ui=always `
            clang-format `
              --style file `
              --diff $env:RED3EXT_COMMIT_BEFORE $env:RED3EXT_COMMIT_AFTER
