name: Release Workflow

on:
  release:
    types: [published]

env:
  RED3EXT_VERSION: ${{ github.ref_name }}
  RED3EXT_BUILD_CONFIG: Release
  RED3EXT_CHECKSUM_ALGORITHM: SHA256

jobs:
  release:
    name: Release ${{ github.ref_name }}
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Create build directory
        run: mkdir build

      - name: Configure
        working-directory: build
        run: |
          cmake `
            -DRED3EXT_CI_RELEASE=ON `
            -DRED3EXT_INSTALL=ON `
            -DRED3EXT_EXTRA_WARNINGS=ON `
            -DRED3EXT_TREAT_WARNINGS_AS_ERRORS=ON `
            "${{ github.workspace }}"

      - name: Build
        working-directory: build
        run: |
          cmake `
            --build . `
            --config ${env:RED3EXT_BUILD_CONFIG}

      - name: Install
        working-directory: build
        run: |
          cmake `
            --install . `
            --prefix "${{ github.workspace }}/build/install" `
            --config ${env:RED3EXT_BUILD_CONFIG}

      - name: Create release package
        working-directory: build/install
        run: 7z a -r red3ext-${env:RED3EXT_VERSION}.zip *.dll *.txt

      - name: Create debug symbols package
        working-directory: build/install
        run: 7z a -r red3ext-symbols-${env:RED3EXT_VERSION}.zip *.pdb

      - name: Compute package checksum
        working-directory: build/install
        run: |
          $fileHash = Get-FileHash -Algorithm ${env:RED3EXT_CHECKSUM_ALGORITHM} -Path red3ext-${env:RED3EXT_VERSION}.zip
          $fileHash | Format-List

          $checksum = $fileHash.Hash
          Add-Content -LiteralPath ${env:GITHUB_ENV} -Encoding UTF8 -Value "RED3EXT_CHECKSUM_PACKAGE=${checksum}"

      - name: Compute debug symbols checksum
        working-directory: build/install
        run: |
          $fileHash = Get-FileHash -Algorithm ${env:RED3EXT_CHECKSUM_ALGORITHM} -Path red3ext-symbols-${env:RED3EXT_VERSION}.zip
          $fileHash | Format-List

          $checksum = $fileHash.Hash
          Add-Content -LiteralPath ${env:GITHUB_ENV} -Encoding UTF8 -Value "RED3EXT_CHECKSUM_SYMBOLS=${checksum}"

      - name: Upload assets
        uses: softprops/action-gh-release@v2
        with:
          append_body: true
          body: |

            ## Checksums

            - red3ext-${{ env.RED3EXT_VERSION }}.zip
              - **${{ env.RED3EXT_CHECKSUM_ALGORITHM }}**: ${{ env.RED3EXT_CHECKSUM_PACKAGE }}
            - red3ext-symbols-${{ env.RED3EXT_VERSION }}.zip
              - **${{ env.RED3EXT_CHECKSUM_ALGORITHM }}**: ${{ env.RED3EXT_CHECKSUM_SYMBOLS }}
          files: |
            build/install/red3ext-${{ env.RED3EXT_VERSION }}.zip
            build/install/red3ext-symbols-${{ env.RED3EXT_VERSION }}.zip
