name: Release Workflow

on:
  push:
    tags: '*'

env:
  RED3EXT_CONFIG: Release
  RED3EXT_VERSION: ${{ github.ref_name }}
  RED3EXT_HASH_ALGORITHM: SHA256

jobs:
  release:
    name: Release ${{ github.ref_name }}
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Create build directory
        run: mkdir build

      - name: Configure
        working-directory: build
        run: |
          cmake `
            -DRED3EXT_CI_RELEASE=ON `
            -DRED3EXT_INSTALL=ON `
            -DRED3EXT_EXTRA_WARNINGS=ON `
            -DRED3EXT_TREAT_WARNINGS_AS_ERRORS=ON `
            "${{ github.workspace }}"

      - name: Build
        working-directory: build
        run: |
          cmake `
            --build . `
            --config ${env:RED3EXT_CONFIG}

      - name: Install
        working-directory: build
        run: |
          cmake `
            --install . `
            --prefix "${{ github.workspace }}/build/install" `
            --config ${env:RED3EXT_CONFIG}

      - name: Create ZIP
        working-directory: build/install
        run: 7z a -r red3ext-${env:RED3EXT_VERSION}.zip *.dll *.txt

      - name: Create symbols ZIP
        working-directory: build/install
        run: 7z a -r red3ext-symbols-${env:RED3EXT_VERSION}.zip *.pdb

      - name: Compute ZIP's checksum
        working-directory: build/install
        run: |
          $Hash = Get-FileHash -Algorithm ${env:RED3EXT_HASH_ALGORITHM} -Path red3ext-${env:RED3EXT_VERSION}.zip
          $Hash | Format-List

          $Checksum = $Hash | ForEach-Object { $_.Hash }
          echo "RED3EXT_ZIP_SHA256=${Checksum}" | Out-File -FilePath ${env:GITHUB_ENV} -Encoding UTF8 -Append

      - name: Compute symbols ZIP's checksum
        working-directory: build/install
        run: |
          $Hash = Get-FileHash -Algorithm ${env:RED3EXT_HASH_ALGORITHM} -Path red3ext-symbols-${env:RED3EXT_VERSION}.zip
          $Hash | Format-List

          $Checksum = $Hash | ForEach-Object { $_.Hash }
          echo "RED3EXT_SYMBOLS_SHA256=${Checksum}" | Out-File -FilePath ${env:GITHUB_ENV} -Encoding UTF8 -Append

      - name: Upload assets
        uses: softprops/action-gh-release@v1
        with:
          append_body: true
          body: |

            ## Checksums

            - red3ext-${{ env.RED3EXT_VERSION }}.zip
              - **${{ env.RED3EXT_HASH_ALGORITHM }}**: ${{ env.RED3EXT_ZIP_SHA256 }}
            - red3ext-symbols-${{ env.RED3EXT_VERSION }}.zip
              - **${{ env.RED3EXT_HASH_ALGORITHM }}**: ${{ env.RED3EXT_SYMBOLS_SHA256 }}
          files: |
            build/install/red3ext-${{ env.RED3EXT_VERSION }}.zip
            build/install/red3ext-symbols-${{ env.RED3EXT_VERSION }}.zip
